language: node_js
node_js:
- node
cache: yarn
before_script:
- yarn global add greenkeeper-lockfile
- greenkeeper-lockfile-update
script: yarn run test:ci
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- greenkeeper-lockfile-upload
