export const AUTH_TOKEN = 'token';
export const CURRENT_USER = 'current_user';
export const reactUrl = '/react.js';
export const reactDomUrl = '/react-dom.js';
export const faviconUrl =
    'data:image/x-icon;base64,AAABAAEAIB0AAA=';
export const stylesUrl = '/style.min.css';
export const browserUrl = '/browser.js';
export const browserMapUrl = '/browser.js.map';
export const propsUrl = '/app-props.json';
export const containerId = 'content';